from fastapi import FastAPI, Request, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import uvicorn
import json
import asyncio
from rag_memory import qa_chain, format_chunks


app = FastAPI(title="RAG Chat API")


# Add this BEFORE defining endpoints
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://144.174.11.43",
        "http://144.174.11.43/joomla_hello",
        "http://localhost",
        "*"
        ],  # or ["https://your-joomla-domain.com"]
    allow_credentials=True,
    allow_methods=["POST", "GET", "OPTIONS","*"],  # allow POST, OPTIONS, GET, etc.
    allow_headers=["*"],
)

# in-memory chat history (per session this can be improved with DB/Redis)
chat_histories = {}

class Query(BaseModel):
    question: str
    
# ------------------------------------------------------------
# POST /chat → Main chatbot endpoint
# ------------------------------------------------------------
@app.post("/chat")
async def chat(query: Query, x_session_id: str = Header(...)):
    """
    Accepts a user's question and a session ID, then returns:
      - Answer generated by the RAG chain
      - Reformulated standalone question
      - Retrieved context chunks
      - Updated chat history
      - Internal prompt representations (for debugging)
    """
    
    # Validate the question field
    if not query.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")
    

    # Retrieve session-specific chat history (or create new)
    history = chat_histories.get(x_session_id, [])
  
    # Generate a standalone version of the current question
    standalone_q = qa_chain.question_generator.run({
        "chat_history": list(history),
        "question": query.question,
    })

        # Run the RAG chain: pass question + chat history
    result = qa_chain({
        "question": query.question,
        "chat_history": list(history)
    })
    answer = result["answer"]  

    # Update session-specific chat history
    # Compute the new question number (e.g., Q1, Q2, Q3...)
    q_num = len(history) + 1
    history.append((f"Q{q_num}: {standalone_q}", f"A: {answer}"))  
    chat_histories[x_session_id] = history


    # Build internal prompts for debugging / analysis
    condense_prompt_text = qa_chain.question_generator.prompt.format(
        chat_history=history[:-1],
        question=query.question
    )


    fake_context = "The context here are the retrieved chunks."     # You can optionally include retrieved context if available
    custom_prompt_text = qa_chain.combine_docs_chain.llm_chain.prompt.format(
        context=fake_context,
        question=standalone_q
    )

    src_docs = result.get("source_documents", []) or []
    retrieved_chunks = format_chunks(src_docs, max_items=10, max_chars=5000)


    # Return the structured API response
    return {
        "question": query.question,
        "standalone_question": standalone_q,
        "answer": answer,
        "retrieved_chunks": retrieved_chunks,
        "chat_history": history[:-1],
        "condense_prompt_text": condense_prompt_text,
        "custom_prompt_text": custom_prompt_text
    }

# ------------------------------------------------------------
# POST /chat/stream → Streaming chatbot endpoint
# ------------------------------------------------------------
@app.post("/chat/stream")
async def chat_stream(query: Query, x_session_id: str = Header(...)):
    """
    Streaming endpoint that sends LLM tokens as Server-Sent Events (SSE).
    Compatible with Joomla and other frontend frameworks.
    """
    
    # Validate the question field
    if not query.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")
    
    # Retrieve session-specific chat history (or create new)
    history = chat_histories.get(x_session_id, [])
    
    async def generate_stream():
        """Generator function that yields streaming tokens"""
        try:
            # Generate standalone question first (non-streaming)
            standalone_q = qa_chain.question_generator.run({
                "chat_history": list(history),
                "question": query.question,
            })
            
            
            # First, retrieve documents (non-streaming)
            retrieved_docs = await qa_chain.retriever.ainvoke(standalone_q)
            
            # Format the context from retrieved documents
            context = "\n\n".join([doc.page_content for doc in retrieved_docs])
            
            # Get the LLM and prompt from the chain
            llm = qa_chain.combine_docs_chain.llm_chain.llm
            prompt = qa_chain.combine_docs_chain.llm_chain.prompt
            
            # Format the prompt with context and question
            formatted_prompt = prompt.format(context=context, question=standalone_q)
            
            # Stream directly from the LLM - this will stream tokens in real-time
            full_answer = ""
            async for chunk in llm.astream(formatted_prompt):
                # Extract text from the chunk
                if hasattr(chunk, 'content'):
                    token = chunk.content
                elif isinstance(chunk, dict):
                    token = chunk.get('content', chunk.get('text', ''))
                elif isinstance(chunk, str):
                    token = chunk
                else:
                    # Try to get text attribute or convert to string
                    token = getattr(chunk, 'text', str(chunk)) if chunk else ""
                
                if token:
                    full_answer += token
                    # Send each token as it arrives (SSE format)
                    yield f"data: {json.dumps({'type': 'token', 'content': token})}\n\n"
            
            # Send final answer completion
            yield f"data: {json.dumps({'type': 'answer_complete', 'content': full_answer})}\n\n"

            
            # Update chat history
            q_num = len(history) + 1
            history.append((f"Q{q_num}: {standalone_q}", f"A: {full_answer}"))
            chat_histories[x_session_id] = history

            # After generating standalone question
            chat_history_text = "\n".join([f"{q}\n{a}" for q,a in history[:-1]])
            condense_prompt_text = qa_chain.question_generator.prompt.format(
            chat_history=chat_history_text,
            question=query.question
            )
            yield f"data: {json.dumps({'type':'memory', 'content': {'condense_prompt_text':condense_prompt_text, 'chat_history': history[:-1]}})}\n\n"


            # Send standalone question as initial event
            yield f"data: {json.dumps({'type': 'standalone_question', 'content': standalone_q})}\n\n"
            

            fake_context = "The context here are the retrieved chunks."     # You can optionally include retrieved context if available
            custom_prompt_text = qa_chain.combine_docs_chain.llm_chain.prompt.format(
            context=fake_context,
            question=standalone_q
            )
            # yield f"data: {json.dumps({'type':'prompts', 'content': {'custom_prompt_text':custom_prompt_text}})}\n\n"
            # # Format and send source documents
            retrieved_chunks = format_chunks(retrieved_docs, max_items=10, max_chars=5000)
            yield f"data: {json.dumps({'type': 'sources', 'content':{ 'custom_prompt_text': custom_prompt_text, 'retrieved_chunks' : retrieved_chunks}})}\n\n"
            
            # Send completion signal
            yield f"data: {json.dumps({'type': 'done'})}\n\n"
            
        except Exception as e:
            # Send error as event
            import traceback
            error_msg = str(e)
            traceback.print_exc()
            yield f"data: {json.dumps({'type': 'error', 'content': error_msg})}\n\n"
    
    return StreamingResponse(
        generate_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"  # Disable buffering for nginx
        }
    )

@app.get("/")
def root():
    return {"message": "RAG Chatbot API is running!"}


if __name__ == "__main__":
    uvicorn.run("api_memory:app", host="0.0.0.0", port=8000)


